import { DataClassification, DataSubjectType, RetentionPolicyConfig } from './data-governance.types';

export const DATA_CLASSIFICATION_REGISTRY: Record<DataSubjectType, DataClassification> = {
  CANDIDATE: 'HIGHLY_SENSITIVE',
  ORGANIZATION: 'CONFIDENTIAL',
  ATTEMPT: 'HIGHLY_SENSITIVE',
  REPORT: 'HIGHLY_SENSITIVE',
  AUDIT: 'CONFIDENTIAL',
  SNAPSHOT: 'HIGHLY_SENSITIVE',
  PROCTORING_EVENT: 'HIGHLY_SENSITIVE',
  SESSION: 'CONFIDENTIAL',
  CONSENT: 'HIGHLY_SENSITIVE',
};

export const DEFAULT_RETENTION_POLICIES: RetentionPolicyConfig[] = [
  {
    dataType: 'CANDIDATE',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 365,
    archiveAfterDays: 365,
    deleteAfterDays: 1095,
    purgeAfterDays: 1460,
    legalHoldAllowed: true,
    description: 'Perfil de candidato y datos personales usados en procesos de selección.',
  },
  {
    dataType: 'ATTEMPT',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 365,
    archiveAfterDays: 365,
    deleteAfterDays: 1095,
    purgeAfterDays: 1460,
    legalHoldAllowed: true,
    description: 'Intentos de evaluación, estado, trazas de ejecución y metadatos técnicos.',
  },
  {
    dataType: 'REPORT',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 365,
    archiveAfterDays: 365,
    deleteAfterDays: 1095,
    purgeAfterDays: 1460,
    legalHoldAllowed: true,
    description: 'Resultados, puntajes, recomendaciones y detalles psicométricos.',
  },
  {
    dataType: 'SNAPSHOT',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 30,
    archiveAfterDays: 30,
    deleteAfterDays: 90,
    purgeAfterDays: 180,
    legalHoldAllowed: true,
    description: 'Evidencia de proctoring o snapshots asociados a monitoreo.',
  },
  {
    dataType: 'PROCTORING_EVENT',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 180,
    archiveAfterDays: 180,
    deleteAfterDays: 730,
    purgeAfterDays: 1095,
    legalHoldAllowed: true,
    description: 'Eventos de monitoreo, riesgo, comportamiento y evidencia técnica.',
  },
  {
    dataType: 'AUDIT',
    classification: 'CONFIDENTIAL',
    activeDays: 730,
    archiveAfterDays: 730,
    deleteAfterDays: 2190,
    purgeAfterDays: 2555,
    legalHoldAllowed: true,
    description: 'Bitácora de acciones sensibles y accesos a datos.',
  },
  {
    dataType: 'SESSION',
    classification: 'CONFIDENTIAL',
    activeDays: 30,
    archiveAfterDays: 30,
    deleteAfterDays: 90,
    purgeAfterDays: 180,
    legalHoldAllowed: false,
    description: 'Sesiones revocables, tokens hash y metadatos de acceso.',
  },
  {
    dataType: 'CONSENT',
    classification: 'HIGHLY_SENSITIVE',
    activeDays: 1095,
    archiveAfterDays: 1095,
    deleteAfterDays: 2190,
    purgeAfterDays: 2555,
    legalHoldAllowed: true,
    description: 'Consentimientos del candidato y versión aceptada.',
  },
  {
    dataType: 'ORGANIZATION',
    classification: 'CONFIDENTIAL',
    activeDays: 1095,
    archiveAfterDays: 1095,
    deleteAfterDays: 2555,
    purgeAfterDays: 2920,
    legalHoldAllowed: true,
    description: 'Datos tenant, configuración y relaciones de cuenta empresarial.',
  },
];
